# see https://s.apache.org/asfyaml
github:
  description: "Apache Maven Artifact Resolver Ant Tasks"
  homepage: https://maven.apache.org/resolver-ant-tasks/
  labels:
    - java
    - build-management
    - apache-maven
    - maven
    - apache-ant
  del_branch_on_merge: true
  features:
    issues: true